using System;

namespace Win32Types
{
	internal enum ButtonStyle : uint
	{
		BS_PUSHBUTTON,
		BS_DEFPUSHBUTTON,
		BS_CHECKBOX,
		BS_AUTOCHECKBOX,
		BS_RADIOBUTTON,
		BS_3STATE,
		BS_AUTO3STATE,
		BS_GROUPBOX,
		BS_USERBUTTON,
		BS_AUTORADIOBUTTON,
		BS_PUSHBOX,
		BS_OWNERDRAW,
		BS_TYPEMASK = 15u,
		BS_LEFTTEXT = 32u,
		BS_TEXT = 0u,
		BS_ICON = 64u,
		BS_BITMAP = 128u,
		BS_LEFT = 256u,
		BS_RIGHT = 512u,
		BS_CENTER = 768u,
		BS_TOP = 1024u,
		BS_BOTTOM = 2048u,
		BS_VCENTER = 3072u,
		BS_PUSHLIKE = 4096u,
		BS_MULTILINE = 8192u,
		BS_NOTIFY = 16384u,
		BS_FLAT = 32768u,
		BS_RIGHTBUTTON = 32u
	}
}
