using System;

namespace Win32Types
{
	internal enum ImeNotify
	{
		IMN_CLOSESTATUSWINDOW = 1,
		IMN_OPENSTATUSWINDOW,
		IMN_CHANGECANDIDATE,
		IMN_CLOSECANDIDATE,
		IMN_OPENCANDIDATE,
		IMN_SETCONVERSIONMODE,
		IMN_SETSENTENCEMODE,
		IMN_SETOPENSTATUS,
		IMN_SETCANDIDATEPOS,
		IMN_SETCOMPOSITIONFONT,
		IMN_SETCOMPOSITIONWINDOW,
		IMN_SETSTATUSWINDOWPOS,
		IMN_GUIDELINE,
		IMN_PRIVATE
	}
}
