using System;

namespace Win32Types
{
	internal enum StaticControlStyles : uint
	{
		SS_LEFT,
		SS_CENTER,
		SS_RIGHT,
		SS_ICON,
		SS_BLACKRECT,
		SS_GRAYRECT,
		SS_WHITERECT,
		SS_BLACKFRAME,
		SS_GRAYFRAME,
		SS_WHITEFRAME,
		SS_USERITEM,
		SS_SIMPLE,
		SS_LEFTNOWORDWRAP,
		SS_OWNERDRAW,
		SS_BITMAP,
		SS_ENHMETAFILE,
		SS_ETCHEDHORZ,
		SS_ETCHEDVERT,
		SS_ETCHEDFRAME,
		SS_TYPEMASK = 31u,
		SS_REALSIZECONTROL = 64u,
		SS_NOPREFIX = 128u,
		SS_NOTIFY = 256u,
		SS_CENTERIMAGE = 512u,
		SS_RIGHTJUST = 1024u,
		SS_REALSIZEIMAGE = 2048u,
		SS_SUNKEN = 4096u,
		SS_EDITCONTROL = 8192u,
		SS_ENDELLIPSIS = 16384u,
		SS_PATHELLIPSIS = 32768u,
		SS_WORDELLIPSIS = 49152u,
		SS_ELLIPSISMASK = 49152u
	}
}
